services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    environment:
      - DB_USER=bukka
      - DB_PASSWORD=bukka
      - DB_PORT=3306
      - DB_NAME=bukka
      - DB_HOST=db
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: bukka
      MYSQL_PASSWORD: bukka
      MYSQL_DATABASE: bukka
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
