services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - '8080:8080'
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: bukka
      MYSQL_PASSWORD: bukka
      MYSQL_DATABASE: bukka
    ports:
      - '5432:5432'
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
