// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// HealthGet implements GET /health operation.
//
// Endpoint to check the health of the service.
//
// GET /health
func (UnimplementedHandler) HealthGet(ctx context.Context) (r *HealthGetOK, _ error) {
	return r, ht.ErrNotImplemented
}
