CREATE DATABASE IF NOT EXISTS bukka;

USE bukka;

CREATE TABLE IF NOT EXISTS items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    created_at VARCHAR(23) NOT NULL,
    updated_at VARCHAR(23) NOT NULL,
    deleted_at VARCHAR(23) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;